### ISSUE TITLE
NameError: name 'avengers' is not defined

### ISSUE THREAD

**Issue by makdisse** [JackofSpades707/instant_torrent#2]
Clean install, tried to search, got the following error:
```
root@v:~# instanttorrent
enter your search query
> avengers
Traceback (most recent call last):
  File "/usr/local/bin/instanttorrent", line 68, in <module>
    query = input('> ')
  File "<string>", line 1, in <module>
NameError: name 'avengers' is not defined
```

Python and pip versions:

```
root@v:~# pip --version
pip 8.1.1 from /usr/lib/python2.7/dist-packages (python 2.7)
root@v:~# python --version
Python 2.7.12
```

**Comment by JackofSpades707** [comment]
Please uninstall it with pip and reinstall it with pip3 (python3.4+ pip)
Does the issue persist?
